name: Scrapers

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
  - cron: '0 * * * *' 

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install reqs
      run: pip install -r requirements.txt

    - name: Run scraper.py
      env:
        WHURL: ${{ secrets.WHURL }}
      run: |
        python scraper.py
        python notify.py
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add latest pricing data JSON file"
        git push
